version: '3.9'

networks:
  tgCurrencyBot:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

volumes:
  postgres_volume:

services:
  app.backend:
    container_name: app.backend
    build:
      dockerfile: ./docker/app/backend/Dockerfile
    restart: always
    networks:
      - tgCurrencyBot
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - ./src/TgCurrencyBot:/src
      - ./docker/app/backend/logs:/app/logs:cached
    environment:
      ASPNETCORE_URLS: http://+:5000
      TZ: 'Europe/Moscow'
  nginx:
    container_name: nginx
    image: nginx:1.20.1
    depends_on:
      - app.backend
    restart: always
    networks:
      - tgCurrencyBot
    ports:
      - "${NGINX_PORT}:80"
    tty: true
    volumes:
      - ./docker/nginx/logs:/var/log/nginx:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:cached
    environment:
      TZ: 'Europe/Moscow'
  postgresql:
    container_name: postgresql
    build:
      context: ./docker/postgresql
    restart: always
    networks:
      - tgCurrencyBot
    tty: true
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data:rw
    depends_on:
      - app.backend
      - nginx